source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '4.2'

gem 'ahoy_email'
gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'carrierwave'
gem 'chartjs-ror'
gem 'check_appointments'
gem 'chosen-rails'
gem 'coffee-rails'
gem 'compass-rails'
gem 'delayed_job_active_record'
gem 'devise'
gem 'devise_invitable'
gem 'faker', '1.0.1'
gem 'fog'
gem 'font-awesome-rails', '~> 4.0.3.1'
gem 'google-api-client', '<0.9'
gem 'humanize'
gem 'httparty'
gem 'infusionsoft', '~> 1.1.7b'
gem 'json'
gem 'jquery-fileupload-rails'
gem 'jquery-slimscroll-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jscolor-rails'
gem 'lodash-rails'
gem 'mail_form'
gem 'mini_magick', '3.8.0'
gem 'newrelic_rpm'
gem "nested_form", :git => "git://github.com/ryanb/nested_form.git"
gem 'normalize-rails'
gem 'modernizr-rails', '~> 2.6.2.1'
gem 'oj', '~> 2.12.14'
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-google-oauth2'
gem 'paper_trail', '~> 4.0.0'
gem 'populator'
gem 'rack-timeout'
gem 'rails-observers'
gem 'rest_client'
gem 'rmagick', :require => 'RMagick'
gem 'rollbar'
gem 'sass'
gem 'sass-rails'
gem 'selectivizr-rails', '~> 1.0.1'
gem 'sendgrid-ruby'
gem 'simple_form'
gem 'sunspot_rails'
gem 'sunspot_solr'
gem 'test-unit'
gem 'uglifier', '>= 1.0.3'
gem 'will_paginate', '~> 3.0.6'
gem 'woocommerce_api'
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'

group :development, :test do
  gem 'bullet'
  gem 'sqlite3'
  gem 'letter_opener'
  gem 'rspec-rails', '~> 3.0'
  gem 'meta_request'
end

group :production do
  gem 'rails_12factor'
  gem 'pg'
end
